#undef TAPPING_TERM
#define TAPPING_TERM 150

#define COMBO_TERM 20

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "DqdXE/6a0KjL"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 14

#define RGB_MATRIX_STARTUP_SPD 60

