#undef TAPPING_TERM
#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY

#define COMBO_TERM 20
#define COMBO_TERM_PER_COMBO

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "DqdXE/6a0KjL"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 19

#define RGB_MATRIX_STARTUP_SPD 60

#define QUICK_TAP_TERM 100
#define QUICK_TAP_TERM_PER_KEY

#define PERMISSIVE_HOLD_PER_KEY

#define CHORDAL_HOLD
